### ISSUE TITLE
Dan Quotes

### ISSUE THREAD

**Issue by tomouchuu** [uchuuio/disbott#26]
New Module as per Pedro's Suggestion

**Comment by tomopagu** [comment]
Plan is to have:
- `dan`, pull a random quote from the database
- `dan-add`, adds a quote to the database.

The schema for the database would be as below:
```
quote: 'msg',
time: 'time submitted',
submittedBy: msg.Author.Id
```

**Comment by 80cmdude** [comment]
*Bug*

The most recent addition cannot be shown ever when requested

This is because the rounding always rounds up to the nearest integer and cannot roll 0. Therefore string in position 0 can never be called

If there is only 1 quote it rolls between 0,0 which is 0 (it basically doesn't roll)

**Comment by 80cmdude** [comment]
Issue Fixed and ready for test.

@tomopagu the database file is in the bin folder so it is being git ignored. We need to find a way to change the location of this file

**Comment by tomopagu** [comment]
It's easy enough to do, you just modify the path on https://github.com/paguco/disbott/blob/c%23/Disbott/Modules/Quotes/QuotesMethod.cs#L20 and it'll create the database there if not existed. 

I guess best thing would be to make a db folder to contain these files, though this will still be ignored from git as there could be sensitive information in there but it'll be created when hosting and we'll persist that on the server.

**Comment by tomopagu** [comment]
Quotes 100% Tested (Aside from Views) as of: 821a9dd418a052929a59b3f640665742e6de0554

@80cmdude I supposed we best wait for the DB update before closing this?

**Comment by tomopagu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Quotes Module](https://trello.com/c/VB0JJ8LW/10-quotes-module)

**Comment by tomouchuu** [comment]
Closing as tested!
