### ISSUE TITLE
Poll Module

### ISSUE THREAD

**Issue by tomouchuu** [uchuuio/disbott#32]
As part of migrating from JS to C#

**Comment by 80cmdude** [comment]
Currently done the basic version. Just storing the answer to polls in a local object. Plan is to move that into a database. Will need the help of @tomopagu beacuse i cant seem to find an easy way to ammend a database entry using litedb.

**Comment by tomopagu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Poll Module](https://trello.com/c/8PPWents/12-poll-module)

**Comment by tomouchuu** [comment]
Closing as done & tested!
